platform :ios, "8.0"

target :'BaiSiBuDeJie' do

pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.0'

end
